name: firebase_bloc_analytics
description: Easy integrate you app with multiple analytics tracker, integrate with Firebase Analytics, Crashlytics and others
version: 0.7.0
author: guitcastro <guilherme.torres.castro@gmail.com>
homepage: https://github.com/guitcastro/flutter_bloc_analytics

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^5.0.11
  bloc_analytics: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ">=1.9.4"
  test_coverage: ^0.4.0
  mockito: ^4.1.1
