name: firebase_bloc_analytics
description: Easy integrate you app with multiple analytics tracker, integrate with Firebase Analytics, Crashlytics and others
version: 0.1.0
author: guitcastro <guilherme.torres.castro@gmail.com>
homepage: https://github.com/guitcastro/flutter_bloc_analytics

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  bloc_analytics: ^0.1.0
  firebase_analytics: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.2.0
  test_api: ^0.2.1
  mockito: ^4.0.0